networks:
  dokploy-network:

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dokploy-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - admin
      - front
    networks:
      - dokploy-network

  admin:
    build:
      context: ./pcrm-admin
    depends_on:
      - mongodb
    networks:
      - dokploy-network
    environment:
      - ENV_FILE=${ENV_FILE:-.env}

  front:
    build:
      context: ./pcrm-front
    depends_on:
      - admin
    networks:
      - dokploy-network